version: '3.8'

services:
  backend:
    image: krishnapriyap/mern_backend:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=172.24.0.2
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mysql
    networks:
      - my_network

  frontend:
    image: krishnapriyap/mern_frontend:latest
    ports:
      - "3000:3000"

  mysql:
    image: krishnapriyap/mern-mysql
    container_name: mysql
    restart: always
    environment:  
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  code-server:
    image: krishnapriyap/merntest:latest
    environment:
      - PASSWORD=test
    ports:
      - "8280:8080"
    volumes:
      - user_workspace_200:/home/coder/project
    command: ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none"]
    networks:
      - my_network

volumes:
  mysql-data:
  user_workspace_200:
    driver: local

networks:
  my_network:
    driver: bridge
